AWSTemplateFormatVersion: 2010-09-09
Description: My template to deploy a vpc
Resources:
  NewVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'